// Package webui holds the built frontend, embedded into the binary.
//
// The contents of dist/ are generated by `make ui` (Vite writes here directly)
// and are not committed, apart from a placeholder that keeps the directory
// present so a fresh clone still compiles.
package webui

import (
	"embed"
	"io/fs"
)

// distFS is the built frontend.
//
// The all: prefix matters: default embed rules skip files whose names begin
// with "." or "_", and it is also what lets the committed .gitkeep satisfy the
// pattern on a clone where the UI has not been built. Without it, a fresh
// checkout would fail to compile rather than merely lacking a UI.
//
//go:embed all:dist
var distFS embed.FS

// FS returns the frontend rooted at dist, so a request for "/index.html"
// resolves rather than "/dist/index.html".
//
// The second return value reports whether a real UI is present. A clone that
// has not run `make ui` embeds only the placeholder, and the daemon should
// serve the API alone rather than a broken page.
func FS() (fs.FS, bool) {
	sub, err := fs.Sub(distFS, "dist")
	if err != nil {
		return nil, false
	}
	if _, err := fs.Stat(sub, "index.html"); err != nil {
		return nil, false
	}
	return sub, true
}
