apiVersion: v2
name: rcon-ui
description: Self-hosted RCON client for game servers
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/juajotagon/rcon-ui
sources:
  - https://github.com/juajotagon/rcon-ui
keywords:
  - rcon
  - minecraft
  - gameserver
