{{- include "rcon-ui.validate" . -}}
{{- if or (and .Values.auth.token (not .Values.auth.existingSecret)) (and .Values.sealingKey.value (not .Values.sealingKey.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rcon-ui.fullname" . }}
  labels: {{- include "rcon-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
  {{ .Values.auth.tokenKey }}: {{ .Values.auth.token | quote }}
  {{- end }}
  {{- if and .Values.sealingKey.value (not .Values.sealingKey.existingSecret) }}
  {{ .Values.sealingKey.key }}: {{ .Values.sealingKey.value | quote }}
  {{- end }}
{{- end }}
